[package]
name = "Rattus"
version = "0.1.0"
authors = ["Corallus-Caninus <ward.joshua92@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "Rattus"
path = "src/lib.rs"
[dependencies]
x11 = "2.18.2"
inputbot = { git = "https://github.com/Corallus-Caninus/inputbot.git", branch = "develop" }
#[dependencies.inputbot]
#path = "../InputBot"
