#parameters for Rattus
#values are listed as microsecond delays (smaller is faster)
click_speed=200
fast_speed=30
medium_speed=10
slow_speed=2
# fast_speed = 1
# medium_speed =1
# slow_speed = 1
fast_arrow_speed=5000
medium_arrow_speed=40000
slow_arrow_speed=120000
numpad_speed=120000
