#parameters for Rattus
#values are listed as microsecond delays (smaller is faster)
click_speed=5
# fast_speed=300
# medium_speed=3000
# slow_speed=20000
fast_speed = 9
medium_speed = 70
slow_speed = 150
fast_arrow_speed=5000
medium_arrow_speed=40000
slow_arrow_speed=120000
numpad_speed=120000
